### PR TITLE
Rename speech-onprem chart and slim packaged file.

### PR DESCRIPTION
**Pull request by anthonsu**
As required, renamed the helm chart from **speech-onprem** to **cognitive-services-speech-onpremise**.
Slim the helm chart packaged file by removing unnecessary files inside.

### CODE REVIEW

**Comment by anthonsu** [comment]
@BrendanMWalsh, @dbanda, @IEvangelist

**Comment by IEvangelist** [comment]
I agree with changing the name, but I'm now leaning away from the `onprem` verbiage. It's a helm chart that contains two speech services, why are we binding it to onprem? It can be installed in the cloud for example, and that would be a perfectly acceptable use case.

I suggest renaming it to: `cognitive-services-speech`

**Comment by anthonsu** [comment]
> I agree with changing the name, but I'm now leaning away from the `onprem` verbiage. It's a helm chart that contains two speech services, why are we binding it to onprem? It can be installed in the cloud for example, and that would be a perfectly acceptable use case.
> 
> I suggest renaming it to: `cognitive-services-speech`

So this helm chart is specific for onpremise use case only right? And that is why it uses onpremise docker contain image instead of the cloud server version.
Basically it is different from what we have in cloud.

**Comment by IEvangelist** [comment]
Hey @anthonsu, I guess I didn't know if that was true or not. I thought that it was just the container images for each service, without any notion of onprem. If that is true, I'm fine with the name. It just kind of feels weird, how are the images different?

**Comment by anthonsu** [comment]
> Hey @anthonsu, I guess I didn't know if that was true or not. I thought that it was just the container images for each service, without any notion of onprem. If that is true, I'm fine with the name. It just kind of feels weird, how are the images different?

Ya, the docker image inside this helm chart is the image for onprem use :)
It basically wraps different layers for onprem use cases.

**Comment by BrendanMWalsh** [comment]
In general our contract with customers is that the image we ship to them is the same image that powers our web APIs. Why do we need a separate image for on-prem here?

**Comment by BrendanMWalsh** [comment]
This commit should also remove the tgz under `repo/speech-onprem/`, right?

**Comment by anthonsu** [comment]
> In general our contract with customers is that the image we ship to them is the same image that powers our web APIs. Why do we need a separate image for on-prem here?

The docker image I use is basically from this https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/speech-container-howto?branch=release-build-cogserv-speech-services
And this helm chart is created with purpose that providing customer an idea of how to use deploy onpremise speech service container into k8s cluster. 
In future, this helm chart (or docker container itself) may be able to let customers to apply their own on premises speech models (or anything else, I don't know yet).
So I'd suggest keeping onpremise key word here.

**Comment by anthonsu** [comment]
> This commit should also remove the tgz under `repo/speech-onprem/`, right?

Yes, it doesn't? Let me verify. Good catch :)

**Comment by anthonsu** [comment]
Ah, it doesn't remove speech-onprem because I synced up with master branch instead of gh-pages.
Let me update.

**Comment by anthonsu** [comment]
./speech-onprem stuff is removed now :)

**Comment by dbanda** [comment]
Just a tiny comment. Can you also add an image for the chart if you have one

**Pull request merged**
